services:
  mysql: 
    image: mariadb:10.6.25    
    container_name: solareye_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: solar_eye
      MYSQL_USER: solar
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - "./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql"

  backend:
    build: "./backend"
    container_name: solareye_backend
    depends_on:
      - mysql
      - simulator
    environment:
      DATABASE_HOST: solareye-db-solar-eye-bd.g.aivencloud.com
      DATABASE_PORT: 16897
      DATABASE_USER: avnadmin
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: defaultdb
      DATABASE_SSL: "true"
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      SIMULADOR_PYTHON: http://simulator:8000
      OPEN_METEO_API_KEY: ${OPEN_METEO_API_KEY:-}
    ports:
      - "3001:3001"

  simulator:
    build: "./solar-eye-simulator"
    container_name: solareye_simulator
    ports:
      - "8000:8000"

  frontend:
    build: "./frontend"
    container_name: solareye_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mysql_data: